service:
  name: giantstar
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    mongoDBHost: '${file(./config/${self:provider.stage}.json):mongoDB.host}'
  region: ap-northeast-2

functions:
  graphql:
    handler: api/graphql.graphqlHandler
    events:
      - http:
          method: post
          path: api/graphql
